# Generated by Django 4.2.9 on 2024-01-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.IntegerField(default=0)),
                ('var2', models.IntegerField(default=0)),
            ],
        ),
    ]
